### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by acocac** [yuwei-cao-git/DRI-EDIA-F4A#4]
The README indicates [two types of licences](https://github.com/yuwei-cao-git/DRI-EDIA-F4A?tab=readme-ov-file#%EF%B8%8F-license): MIT license (code) and Creative Commons Attribution 4.0 International license (for documentation), however only the MIT is visible in the repository. 

You can make both licenses visible in your repo by creating the following two files:

- LICENSE-code: should contain the MIT license.
- LICENSE: replace the MIT license with the CC-BY-4.0 license.

**Comment by yuwei-cao-git** [comment]
license updated
