### ISSUE TITLE
Credits to templates

### ISSUE THREAD

**Issue by acocac** [yuwei-cao-git/DRI-EDIA-F4A#6]
While the README indicates the source of some files in the Reference section, I suggest adding a line indicating the source in each of these files. See an example below for the Contributing guidelines:

----

These Contributing Guidelines have been adapted from the [Contributing Guidelines](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md) of [STEMM Role Models App](https://github.com/KirstieJane/STEMMRoleModels)! (License: MIT)

**Comment by yuwei-cao-git** [comment]
Thank you for reminding me this important info!
